apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  app: nginx
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # Allow one pod to be unavailable during the update
      maxSurge: 1 # Allow one additional pod to be created during the update

  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.20
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort # Change to LoadBalancer if you want to expose it externally
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
